#ifndef __RenderEnv_h
#define __RenderEnv_h


#define BUFFER_OFFSET(i) ((char *)NULL + (i))
#define TEXTURE_OFFSET BUFFER_OFFSET(32)
#define VERTEX_BUFFER_STRIDE 48
#define NORMAL_OFFSET BUFFER_OFFSET(12)
#define POSITION_OFFSET 0
#define VBO_ELEM_SIZE VERTEX_BUFFER_STRIDE
#define EBO_ELEM_SIZE	12
#define POINT_EBO_ELEM_SIZE 4
#define COLOR_OFFSET1 24
#define COLOR_OFFSET2 28
#define EDGE_EBO_ELEM_SIZE	8
#define VERTEX_COLOR_OFFSET1 40
#define VERTEX_COLOR_OFFSET2 44
#define EDGE_ELEM_SIZE  EDGE_EBO_ELEM_SIZE
#define POINT_ELEM_SIZE  POINT_EBO_ELEM_SIZE

#define RM_INCREMENT_COUNT 1000

#endif